### ISSUE TITLE
accuracy of mmpose vs detectron2

### ISSUE THREAD

**Issue by yulong314** [open-mmlab/mmpose#428]
from comparisons of  mmpose vs HRNet [here](https://github.com/open-mmlab/mmpose) and HRNet vs maskrcnn [here](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation), mmpose is more accurate than hrnet, and hrnet is more accurate than detectron2 which is maskrcnn based。
But on my datasets , detectron2  gives better result.
my datasets are small, most have  only  about 50 samples now.
one samples looks like below:
![middle_1043_flip](https://user-images.githubusercontent.com/19659558/104834831-00d66780-58dd-11eb-8141-a25404c28f51.jpg)

Any body have ideas about that?
my detectron2 config:
```
_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  ROI_KEYPOINT_HEAD: 
    NUM_KEYPOINTS: 19
  # WEIGHTS: "/media/sy/1746fa4b-7555-471c-81e9-023fab575569/doc/data/outputs/keypointsTransfersy_v2_3_720_little/model_0000999.pth"
  WEIGHTS: "/mnt/data/samples/models/model_final_04e291keypoints_50.pkl"
  RESNETS: 
    # DEPTH: 50
    DEPTH: 50
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 4
  # BASE_LR: 0.0005
  BASE_LR: 0.0005
  REFERENCE_WORLD_SIZE: 2
  STEPS: (6400, 7200)
  MAX_ITER: 8000
  CHECKPOINT_PERIOD: 2000
OUTPUT_DIR: "/mnt/data/new_mergeDataToModel/models_left_up_nei_dan"  

DATASETS:
  TRAIN: ("sytrain",)
  TEST: ("sytest",)
TEST:
  EVAL_PERIOD: 200
INPUT:
  # RANDOM_FLIP: "vertical"
  RANDOM_FLIP: "none"
  # ROTATION_ANGLES: (0)

  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)  
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280 
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280
```

mmpose config:
```
log_level = 'INFO'
load_from = None
resume_from = None
dist_params = dict(backend='nccl')
workflow = [('train', 1)]
checkpoint_config = dict(interval=50)
evaluation = dict(interval=10, metric='mAP', key_indicator='AP')

optimizer = dict(
    type='Adam',
    lr=5e-4,
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    # warmup=None,
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[400,600,700,800,900])
total_epochs = 1000
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])

channel_cfg = dict(
    num_output_channels=19,
    dataset_joints=19,
    dataset_channel=[
        list(range(19)),
    ],
    inference_channel=list(range(19)))

# model settings
model = dict(
    type='TopDown',
    pretrained='https://download.openmmlab.com/mmpose/top_down/'
    'hrnet/hrnet_w48_coco_384x288_dark-741844ba_20200812.pth',
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(48, 96)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(48, 96, 192)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(48, 96, 192, 384))),
    ),
    keypoint_head=dict(
        type='TopDownSimpleHead',
        in_channels=48,
        out_channels=channel_cfg['num_output_channels'],
        num_deconv_layers=0,
        extra=dict(final_conv_kernel=1, ),
    ),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=False,
        post_process=False,
        shift_heatmap=False,
        unbiased_decoding=False,
        modulate_kernel=11),
    loss_pose=dict(type='JointsMSELoss', use_target_weight=True))

data_cfg = dict(
    image_size=[288, 384],
    heatmap_size=[72, 96],
    num_output_channels=channel_cfg['num_output_channels'],
    num_joints=channel_cfg['dataset_joints'],
    dataset_channel=channel_cfg['dataset_channel'],
    inference_channel=channel_cfg['inference_channel'],
    soft_nms=False,
    nms_thr=1.0,
    oks_thr=0.9,
    vis_thr=0.2,
    bbox_thr=1.0,
    use_gt_bbox=True,
    image_thr=0.0,
    bbox_file='data/coco/person_detection_results/'
    'COCO_val2017_detections_AP_H_56_person.json',
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    # dict(type='TopDownRandomFlip', flip_prob=0.5),
    # dict(
    #     type='TopDownHalfBodyTransform',
    #     num_joints_half_body=8,
    #     prob_half_body=0.3),
    # dict(
    #     type='TopDownGetRandomScaleRotation', rot_factor=40, scale_factor=0.5),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(type='TopDownGenerateTarget', sigma=3, unbiased_encoding=True),
    dict(
        type='Collect',
        keys=['img', 'target', 'target_weight'],
        meta_keys=[
            'image_file', 'joints_3d', 'joints_3d_visible', 'center', 'scale',
            'rotation', 'bbox_score','flip_pairs'
        ]),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score','flip_pairs'

        ]),
]

test_pipeline = val_pipeline


data_root = '/mnt/data/mergeData/result/finally_Merged_dan_left_up_neiba'
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type='TopDownCocoWeijingDataset',
        ann_file=f'{data_root}/train.json',
        img_prefix=f'{data_root}/train/',
        data_cfg=data_cfg,
        pipeline=train_pipeline),
    val=dict(
        type='TopDownCocoWeijingDataset',
        ann_file=f'{data_root}/test.json',
        img_prefix=f'{data_root}/test/',
        data_cfg=data_cfg,
        pipeline=train_pipeline),
    test=dict(
        type='TopDownCocoWeijingDataset',
        ann_file=f'{data_root}/test_xiashen.json',
        img_prefix=f'{data_root}/test_xiashen/',
        data_cfg=data_cfg,
        pipeline=train_pipeline),
)
```
